apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-api
  namespace: NAMESPACE
  labels:
    app: alex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-api
  template:
    metadata:
      labels:
        app: alex-api
    spec:
      containers:
      - name: alex-api
        image: ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/apiapp:IMAGEVERSION
        ports:
        - containerPort: 80
