apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-web
  namespace: NAMESPACE
  labels:
    app: alex-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-web
  template:
    metadata:
      labels:
        app: alex-web
    spec:
      containers:
      - name: alex-web
        image: ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/webapp:IMAGEVERSION
        ports:
        - containerPort: 80
